pipeline-settings: &pipeline-settings
  settings:
    capacity: 32768
    max_event_size: 524288
    pool: low_memory

pipeline-input-settings: &pipeline-input-settings
  type: file
  workers_count: 16
  offsets_op: 'reset'
  persistence_mode: 'async'
  paths:
    include:
      - '/var/file.d/logs/*.log'

pipeline-output-settings: &pipeline-output-settings
  type: elasticsearch
  index_format: logs-index
  connection_timeout: 20s
  workers_count: 32
  batch_flush_timeout: 200ms

pipelines:
  elasticsearch:
    <<: *pipeline-settings

    input:
      <<: *pipeline-input-settings
      offsets_file: '/var/file.d/offsets/elasticsearch-offsets.yaml'

    output:
      <<: *pipeline-output-settings
      endpoints:
        - http://elastic:9200/
