scrape_configs:
  - job_name: 'cadvisor'
    scrape_interval: 30s
    metric_relabel_configs:
      - action: labeldrop
        regex: 'container_label_.*'
    static_configs:
      - targets: [ 'cadvisor:8080' ]
  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter:9100' ]
      - targets: [ 'du-exporter:9995' ]
  - job_name: 'filed'
    static_configs:
      - targets: [ 'filed:9000' ]
  - job_name: 'seq-db'
    static_configs:
      - targets: [ 'seq-db:9200' ]
