server:
  http_addr: "0.0.0.0:5555"
  grpc_addr: "0.0.0.0:5556"
  debug_addr: "0.0.0.0:5557"
clients:
  seq_db_addrs:
    - "seq-db-proxy:9004"
  seq_db_timeout: 15s
  seq_db_avg_doc_size: 100
  request_retries: 3
  proxy_client_mode: "grpc"
  grpc_keepalive_params:
    time: 10s
    timeout: 10s
    permit_without_stream: true
handlers:
  seq_api:
    seq_cli_max_search_limit: 10000
    max_search_limit: 1000
    max_search_total_limit: 100000
    max_search_offset_limit: 100000
    max_export_limit: 10000
    max_parallel_export_requests: 1
    max_aggregations_per_request: 3
