services:
  seq-db-proxy:
    build:
      context: ../
      dockerfile: build/package/Dockerfile
    volumes:
      - "./config.quickstart.yaml:/seq-db/config.yaml"
      - "../tests/data/mappings/:/seq-db/mappings/"
    ports:
      - "9002:9002" # Default HTTP port
      - "9004:9004" # Default gRPC port
      - "9200:9200" # Default debug port
    command: --mode proxy --config=config.yaml
    depends_on:
      - seq-db-store
  
  seq-db-store:
    build:
      context: ../
      dockerfile: build/package/Dockerfile
    volumes:
      - "./config.quickstart.yaml:/seq-db/config.yaml"
      - "../data/:/seq-db/data/"
      - "../tests/data/mappings/:/seq-db/mappings/"
    command: --mode store --config=config.yaml

  minio:
    image: quay.io/minio/minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
