services:
  seq-ui:
    image: ghcr.io/ozontech/seq-ui:latest
    volumes:
      - ./config.seq-ui.yaml:/seq-ui/config.yaml
    ports:
      - "5555:5555" # Default HTTP port
      - "5556:5556" # Default gRPC port
      - "5557:5557" # Default debug port
    command: --config config.yaml

  seq-db-proxy:
    image: ghcr.io/ozontech/seq-db:latest
    volumes:
      - "./config.quickstart.yaml:/seq-db/config.yaml"
      - "./mappings.yaml:/seq-db/mappings.yaml"
    ports:
      - "9002:9002" # Default HTTP port
      - "9004:9004" # Default gRPC port
      - "9200:9200" # Default debug port
    command: --mode proxy --config=config.yaml
    depends_on:
      - seq-db-store

  seq-db-store:
    image: ghcr.io/ozontech/seq-db:latest
    volumes:
      - "./config.quickstart.yaml:/seq-db/config.yaml"
      - "./data/:/seq-db/data/"
      - "./mappings.yaml:/seq-db/mappings.yaml"
    command: --mode store --config=config.yaml

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
