version: "3"

services:
  seq-db:
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: "8GB"
    image: ghcr.io/ozontech/seq-db:v0.61.0
    ports:
      - '9002:9002'
    volumes:
      - ./configs/seqdb:/configs
      - seq-db-data:/seq-db-data
    command:
      --mode=single
      --config=/configs/config.yaml

  filed:
    image: 'ghcr.io/ozontech/file.d:v0.58.1-alpine'
    deploy:
      resources:
        limits:
          memory: "12GB"
    volumes:
      - ./dataset/:/var/file.d/logs/
      - filed-offsets:/var/file.d/offsets
      - ./configs/file.d/seq-db.yaml:/usr/share/file.d/seq-db.yaml
    command: ./file.d --config=/usr/share/file.d/seq-db.yaml
    depends_on:
      - seq-db

volumes:
  seq-db-data:
  filed-offsets:
